### ISSUE TITLE
Error adding DOIs with update.py

### ISSUE THREAD

**Issue by virginiascarlett** [JaneliaSciComp/dis-utilities#1]
Getting an error while attempting to add this week's DOIs:

![Screenshot 2024-06-06 at 9 19 25 AM](https://github.com/JaneliaSciComp/dis-utilities/assets/22207296/f7f7b80d-58a6-4df2-bbef-e1f7f6794ec3)

I get the same error whether I try to add one DOI or several from file. Thanks!

**Comment by robsv** [comment]
Can you upgrade doi_common in your virtual env? I've been making pudates to that module.

**Comment by virginiascarlett** [comment]
Ah, yes that fixed it!
