### ISSUE TITLE
add_preprint.py: gracefully handle DOIs not in DB

### ISSUE THREAD

**Issue by virginiascarlett** [JaneliaSciComp/dis-utilities#101]
Would be great if the script could interactively prompt the user, e.g. "<DOI> is not in the database. Add it to database now?" and then it will create the preprint relation

**Comment by virginiascarlett** [comment]
Whoops, just noticed that this is a duplicate of the last comment in #29

**Comment by robsv** [comment]
Closing issue - as noted, it's a duplicate
