### ISSUE TITLE
doi_common.get author details (not get_doi_record)

### ISSUE THREAD

**Issue by virginiascarlett** [JaneliaSciComp/dis-utilities#112]
I've discovered why I am invoking this with the doi collection as the second argument. Because using the orcid collection or leaving it blank throws an error. Not sure if this is just a documentation issue or a functionality issue.![Image](https://github.com/user-attachments/assets/c9d66652-f6f1-45bb-88a6-bb487f77ee64)

**Comment by robsv** [comment]
Yesterday we were looking at get_author_details, which takes as input the dois collection record, and an optional collection object for the orcid collection.
get_doi_record takes as input the DOI and the collection object for the dois collection

(venv) svirskasr@svirskasr-lm10 bin % python3
Python 3.10.15 (main, Sep  7 2024, 00:20:06) [Clang 15.0.0 (clang-1500.3.9.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from operator import attrgetter
>>> import jrc_common.jrc_common as JRC
>>> import doi_common.doi_common as DL
>>> dbconfig = JRC.get_config("databases")
>>> dbo = attrgetter("dis.prod.read")(dbconfig)
>>> DB = {'dis': JRC.connect_database(dbo)}
>>> rec = DL.get_doi_record('10.1007/s12264-024-01253-8', DB['dis']['dois'])
>>> print(DL.get_author_details(rec, DB['dis']['orcid']))
[{'paper_orcid': '0000-0002-3457-4462', 'family': 'Ahrens', 'given': 'Misha B.', 'is_first': True, 'is_last': True, 'orcid': '0000-0002-3457-4462', 'in_database': True, 'janelian': True, 'asserted': False, 'alumni': False, 'validated': True, 'match': 'ORCID', 'group': 'Misha Ahrens Lab', 'group_code': '093327', 'tags': ['CellMap', 'Misha Ahrens Lab'], 'employeeId': '49301', 'userIdO365': 'AHRENSM@hhmi.org'}]
