### ISSUE TITLE
Allow entry of user records in the orcid collection without ORCIDs.

### ISSUE THREAD

**Issue by robsv** [JaneliaSciComp/dis-utilities#12]
- Modify update_orcid.py to allow entry of user records without ORCIDs
- Modify name_match.py (or equivalent fuzzy matching) to allow entry of user records without ORCIDs

**Comment by virginiascarlett** [comment]
Note: I may soon close this issue and replace it with several smaller issues. I'm breaking this down into chunks we can assign to either you or me.

**Comment by robsv** [comment]
update_dois.py already allows for this - this is how I inserted the group leaders without "Janelia" in Employment on ORCID
