### ISSUE TITLE
add id to ORCID in doi_common

### ISSUE THREAD

**Issue by virginiascarlett** [JaneliaSciComp/dis-utilities#21]
Another little function that I will want eventually: 
add_id_to_existing_orcid: (Name is just a suggestion, I like long variable names.) Given an ORCID, add an employee ID to an ORCID record that already exists. Throw an error if no record exists for the given ORCID.

**Comment by robsv** [comment]
def update_existing_orcid(lookup=None, add=None, coll=None, lookup_by='employeeId'):
    ''' Update a single row in the orcid collection
        Keyword arguments:
          lookup: lookup value
          add: data to insert/update
          lookup_by: "orcid" or "employeeId"
          coll: orcid collection
        Returns:
          row from collection (or None if update was not performed)
    '''

**Comment by virginiascarlett** [comment]
Tried it out, looks to good to me!
