### ISSUE TITLE
Create ORCID record w/o an ORCID in doi_common

### ISSUE THREAD

**Issue by virginiascarlett** [JaneliaSciComp/dis-utilities#22]
Another little function that I'll probably want eventually: 
create_orcid_record: I would like to be able to create an ORCID record for someone who doesn't have an ORCID. I can supply the employee ID + any other employee metadata you need.

**Comment by virginiascarlett** [comment]
I will pass along the employeeId, a list of given names, a list of family names, and optional ORCID. Middle initial(s) should go in given names. Function needs to raise an error if any record with either that ORCID or that employeeId already exists.

**Comment by robsv** [comment]
`def add_orcid(eid, coll, given=None, family=None, orcid=None, write=True):
    ''' Add a record to the orcid collection
        Keyword arguments:
          eid: employeeId
          coll: orcid collection
          given: list of given names
          family: list of family names
          orcid: ORCID
          write: write to orcid collection
        Returns:
          New record
    '''`

**Comment by robsv** [comment]
```
def add_orcid(eid, coll, given=None, family=None, orcid=None, write=True):
    ''' Add a record to the orcid collection
        Keyword arguments:
          eid: employeeId
          coll: orcid collection
          given: list of given names
          family: list of family names
          orcid: ORCID
          write: write to orcid collection
        Returns:
          New record
    '''
```

**Comment by virginiascarlett** [comment]
Works!
