### ISSUE TITLE
Manually add preprint relations

### ISSUE THREAD

**Issue by virginiascarlett** [JaneliaSciComp/dis-utilities#29]
This is a big one. Need to handle cases where the paper and the preprint are in the database, but there's nothing to indicate the relationship, because it wasn't recorded in crossref. Example: 
paper: https://doi.org/10.1083/jcb.202311126
preprint: https://doi.org/10.1101/2023.11.29.569289

I'd like to be able to manually add preprint info if it isn't there already. For now, please start by assuming that I have already found the preprint on Google. (This discovery step is automatable, but I'd rather not automate it any time soon because it's extremely quick to discover preprints manually.)
End goals are:
1. to have manually-added preprint relations show up on the dis responder interface and 
2. send them to Tiago et al. for the new Janelia.org.

I'll reach out to Tiago, Sulav and Ryan next week about how they want to handle preprint relations.

**Comment by robsv** [comment]
Started work on code to assign jrc_preprint based on user-specified primary DOI and its preprint.
I can apply a quick heuristic for a first cut at simple automation - aggregate duplicate titles and user first/last author names to validate.

**Comment by virginiascarlett** [comment]
Here's an example of a preprint relation that wasn't picked up in our database:
https://doi.org/10.48550/arXiv.2404.04726
https://doi.org/10.1038/s41598-024-68918-2

**Comment by virginiascarlett** [comment]
I think this is covered by the keys to the kingdom function. I'll test that and then close this issue.

**Comment by virginiascarlett** [comment]
Update: Rob will write a simple script to update preprints from the command line

**Comment by virginiascarlett** [comment]
Feature: if one of the DOIs is not present in the database, add it to the database
