### ISSUE TITLE
Citations for arXiv DOIs

### ISSUE THREAD

**Issue by virginiascarlett** [JaneliaSciComp/dis-utilities#3]
This is kind of a low-priority issue. As far as I can tell, a request to the citations endpoint with an arXiv DOI throws the following error:
```
Failed to retrieve data. Status code: 500.
 Error message: INTERNAL SERVER ERROR
```
Would be nice to get that working. 
The DOI I was using to test this is: 10.48550/arXiv.2405.12385

**Comment by robsv** [comment]
There was an issue with author lookup - fixed this morning.

curl https://dis.int.janelia.org/citation/dis/10.48550/arXiv.2405.12385
{"data":"Selzer, GJ, Rueden, CT, Hiner, MC, Evans, EL, Kolb, D, Wiedenmann, M, Birkhold, C, Buchholz, T, Helfrich, S, Northan, B, Walter, A, Schindelin, J, Pietzsch, T, Saalfeld, S, Berthold, MR, Eliceiri, KW. SciJava Ops: An Improved Algorithms Framework for Fiji and Beyond. https://doi.org/10.48550/arXiv.2405.12385.","rest":{"elapsed_time":"0:00:00.008289","endpoint":"show_citation","error":false,"pid":6,"requester":"172.31.34.3","row_count":1,"source":"mongo","url":"http://dis.int.janelia.org/citation/dis/10.48550/arXiv.2405.12385"}}
