### ISSUE TITLE
Limit tags to relevant supOrg codes

### ISSUE THREAD

**Issue by virginiascarlett** [JaneliaSciComp/dis-utilities#31]
When choosing tags for this paper: [10.1093/nar/gkae559](https://doi.org/10.1093/nar/gkae559), I noticed that there was some redundancy in tags:

![Image](https://github.com/JaneliaSciComp/dis-utilities/assets/22207296/0fa4573d-8051-4eab-9972-7c93389c3eeb)

We should limit the tags to only the supOrg codes that are relevant to Janelia.org. Kelsey Jones told me that she has some people working on integrating the supOrg codes into janelia.org, at Sulav's request. This will also include the 4 research areas. This should be ready by the end of July. I will check in with Kelsey and Sulav then to make sure we have the list of which supOrg codes are actually integrated into the website.

**Comment by robsv** [comment]
Another example...

![Image](https://github.com/user-attachments/assets/459c7152-2e4e-49c9-8e07-0dcbe15ffb3d)

**Comment by virginiascarlett** [comment]
There is a definitive list: https://pod-monitor.hhmi.org/admin/supervisory-org-janelia
But it's not available through any API. We talked to Tiago and he says it's fine to send redundant SupOrg codes, so I will just check ALL relevant boxes. And Tiago will use the tags that he needs.
