### ISSUE TITLE
another quirky DOI

### ISSUE THREAD

**Issue by virginiascarlett** [JaneliaSciComp/dis-utilities#34]
This one is in CrossRef, so I'm not sure why it isn't being added to the database: 10.1093/bioinformatics/btae441

![Image](https://github.com/JaneliaSciComp/dis-utilities/assets/22207296/8f32800e-c608-46ac-a66d-140b9baf5e60)

**Comment by robsv** [comment]
This is already in the database:
[https://dis.int.janelia.org/doiui/10.1093/bioinformatics/btae441](https://dis.int.janelia.org/doiui/10.1093/bioinformatics/btae441
)
When you run the program on a DOI that's already in the database, it will update it only if it needs to be updated (it looks at the update date on Crossref).
If you want to force an update, use the --force command line parm.

**Comment by virginiascarlett** [comment]
Huh. Okay I swear when I posted this this morning, DIS responder definitely said "this DOI is not stored locally in the database". Maybe there was a lag, or something...
