### ISSUE TITLE
Feature request: guess labs/teams at insertion time

### ISSUE THREAD

**Issue by virginiascarlett** [JaneliaSciComp/dis-utilities#5]
Maybe this is already on your roadmap...

When I do my weekly thing, I'd like to be able to insert a brand new DOI into the database, and then immediately see a best guess at labs and teams. That way, when I create a new publication page on Janelia.org, I have that information to guide me. 

So for instance, if I find this paper: [10.1101/2024.06.05.597673](https://doi.org/10.1101/2024.06.05.597673), which came out 8 days ago, I'd like "Carsen Stringer Lab" to pop up in the jrc metadata. 

Maybe this request will be defunct once the new janelia.org is up, but I'm envisioning a script that would print a best guess at labs/teams, and also give me the ability to update the labs and teams. (Or maybe it will just quietly insert a best guess. Either way is fine. Since we have the jrc_reviewed field, I can see whether it's a manual guess or an automated guess.)

Hopefully that script wouldn't be too hard to make, and pieces of it will continue to be useful for the new j.org.

**Comment by robsv** [comment]
Modified update_dois job to automatically set tags for group leaders for inserts/updates
Stuff that still needs to be done:
1) Fix the DOIs that are already out there to add group leader tags
2) Will start work on program to allow you to assign "best guess" tags from People system affiliations

**Comment by robsv** [comment]
Status as of 2024-06-18:
- At insert time, any group leader in the author list will cause the DOI to be tagged with their lab
- At insert time, any Crossref "name" author (typically a project name) will cause the DOI to be tagged with the project name
- At insert time, any known SciComp Software author will cause the DOI to be tagged with Scientific Computing Software
- Work continues on tagging after insertion

**Comment by virginiascarlett** [comment]
TODO: if they're not a lab head, add ccDescr to their affiliations in the ORCID collection. Add their Managed Teams as well.
