### ISSUE TITLE
Group leader author order

### ISSUE THREAD

**Issue by virginiascarlett** [JaneliaSciComp/dis-utilities#52]
What % of papers have a group leader as the first author? What % of papers have a group leader as last author? I would be most interested in average overall and just 2023.

**Comment by robsv** [comment]
Will replace name in jrc_first_author and jrc_last_author with employeeID

**Comment by virginiascarlett** [comment]
I think this page is almost to my liking, but I'd like a little more clarity on the meaning of that first row in the table; "Non-lab head author".

**Comment by virginiascarlett** [comment]
Let's just remove the first row of the table
