### ISSUE TITLE
Add new names to an existing ORCID record

### ISSUE THREAD

**Issue by virginiascarlett** [JaneliaSciComp/dis-utilities#53]
I'd like to be able to add new names (given and/or family) to an existing ORCID record. I would assume that the most logical way to do this would be to rewrite doi_common.update_existing_orcid(), though I don't super care how the functionality is made available to me. Just that it's available!

**Comment by robsv** [comment]
New function:

add_orcid_name(lookup_by='employeeId', lookup=None, family=None, given=None, coll=None, write=True)

lookup_by is either "orcid" or "employeeId", lookup is the lookup value. Specify family and/or given, and pass in the collection in coll. Returns the new record.
