### ISSUE TITLE
Low priority: doi_common.update_jrc_author

### ISSUE THREAD

**Issue by virginiascarlett** [JaneliaSciComp/dis-utilities#57]
What will we do if there are ever two Janelia employees with the same first and last names? It appears that this function relies on an exact name match to update jrc_author. I could give this function a list of employeeIds instead. Just something to think about.

**Comment by robsv** [comment]
Current solution: do not recognize the author as a Janelian.

**Comment by virginiascarlett** [comment]
What would happen if I added a new record for someone who has the same first and last name as a different record?

**Comment by robsv** [comment]
No problem. In fact, there's nothing stopping us from entering two people with the same ORCID or employeeId. Ideal? No, but necessary - we can only enforce uniqueness of fields where not more than one record has a null value.
