### ISSUE TITLE
Automated email to authors

### ISSUE THREAD

**Issue by virginiascarlett** [JaneliaSciComp/dis-utilities#63]
We should sort out how we'll email authors to let them know that their paper is on (the new) janelia.org. Worst case scenario, it can be manually sent by the librarian. But if we were to automate it, what would that look like? Maybe on Monday morning, a script could look for dois that have a jrc_newsletter date within the last 5 days, and send an email to all Janelia authors?

**Comment by robsv** [comment]
That sounds good, automated emails based on jrc_newsletter date. Two ways to do it - one email per paper, or one per author. I'm sure the authors would appreciate just one email with multiple papers in it. I'm thinking we just do it for journal entries and preprints (maybe book chapters and peer reviews too) - I'm thinking datasets might be too much...
