### ISSUE TITLE
doi_common: single_doi_lookup

### ISSUE THREAD

**Issue by virginiascarlett** [JaneliaSciComp/dis-utilities#70]
Yet another request for a function in doi_common... could I get a function that takes in a DOI and doi collection, and spits out the record for that DOI? Thank you!!

**Comment by robsv** [comment]
Can you use the API?
https://dis.int.janelia.org/doi/10.1016%2Fj.cub.2024.01.015

**Comment by virginiascarlett** [comment]
I definitely could use the API, it's just that all throughout this name_match script I'm using doi_common functions, so it's a little odd to use the API for this one part only. But I can definitely do it if it would take you more than like, 20 minutes to put together a function for me.
