### ISSUE TITLE
Email authors re: ORCID records

### ISSUE THREAD

**Issue by robsv** [JaneliaSciComp/dis-utilities#74]
Email Daniel Reep and  Philip Anschutz and ask them to change their given name in ORCID to just be their given name, and to add their family name.
Email Tyler and ask him to add his surname.
All three authors already have Janelia affiliations in ORCID.

**Comment by virginiascarlett** [comment]
Philip Anschutz is not in the people system, as far as I can tell

**Comment by virginiascarlett** [comment]
Philip Anschutz is alumni. I've emailed Tyler twice now with no response.
