### ISSUE TITLE
Error running update_tags

### ISSUE THREAD

**Issue by virginiascarlett** [JaneliaSciComp/dis-utilities#83]
![Image](https://github.com/user-attachments/assets/0a3364b5-5cfc-46c2-ad8e-89f1586c72b1)

**Comment by robsv** [comment]
I can't reproduce the error. I'm guessing you don't have the latest doi_common library. Please upgrade to the latest doi_common, and also pull the latest update_tags.py (I've added code to handle "authors" with no human name, like "CellMap").
