### ISSUE TITLE
minor bug: DOI in insertion table but not DB

### ISSUE THREAD

**Issue by virginiascarlett** [JaneliaSciComp/dis-utilities#89]
Check out 10.12688/f1000research.146327.2, the second DOI from the bottom:
![Image](https://github.com/user-attachments/assets/2bdb25d7-e0c3-45f0-887e-f5befa0b8ba1)

A search for this DOI in the browser interface says it's not stored locally, yet it has jrc_inserted metadata in that lookup table.

**Comment by robsv** [comment]
Will modify code to strip leading/training spaces
